apiVersion: hub.traefik.io/v1alpha1
kind: APIPlan
metadata:
  name: ociapi-gold-plan
  namespace: apps
spec:
  title: Gold
  description: Gold Plan
  rateLimit:
    limit: 100
    period: 1s
  quota:
    limit: 1000000
    period: 750h
---
apiVersion: hub.traefik.io/v1alpha1
kind: APIPlan
metadata:
  name: ociapi-bronze-plan
  namespace: apps
spec:
  title: Bronze
  description: Bronze Plan
  rateLimit:
    limit: 1
    period: 1s
  quota:
    limit: 1000
    period: 750h
